[colors]
foreground = "#e8e8e8"
background = "#040607"
cursor_bg = "#e8e8e8"
cursor_border = "#e8e8e8"
cursor_fg = "#040607"
selection_bg = "#394b70"
selection_fg = "#e8e8e8"
split = "#63c3dd"
compose_cursor = "#ffad00"
scrollbar_thumb = "#1a1e2e"

ansi = ["#000000", "#fda1a0", "#92cf9c", "#f8e063", "#63c3dd", "#e79cfb", "#7dcfff", "#e0e0e0"]
brights = ["#303030", "#ff9e64", "#5dd48c", "#ffad00", "#4fd1e0", "#ff007c", "#62b9e8", "#e8e8e8"]

[colors.tab_bar]
inactive_tab_edge = "#000000"
background = "#040607"

[colors.tab_bar.active_tab]
fg_color = "#000000"
bg_color = "#63c3dd"

[colors.tab_bar.inactive_tab]
fg_color = "#e8e8e8"