# -----------------------------------------------------------------------------
# MilkOutside Alacritty Colors
# Theme: MilkOutside
# Upstream: https://github.com/color-schemes/milkoutside.nvim/raw/main/extras/alacritty/milkoutside.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#040607'
foreground = '#e8e8e8'

# Normal colors
[colors.normal]
black = '#000000'
red = '#fda1a0'
green = '#92cf9c'
yellow = '#f8e063'
blue = '#63c3dd'
magenta = '#e79cfb'
cyan = '#63c3dd'
white = '#e0e0e0'

# Bright colors
[colors.bright]
black = '#303030'
red = '#ff9e64'
green = '#5dd48c'
yellow = '#ffad00'
blue = '#4fd1e0'
magenta = '#ff007c'
cyan = '#62b9e8'
white = '#e8e8e8'

# Extended colors
[colors.dim]
black = '#000000'
red = '#fda1a0'
green = '#92cf9c'
yellow = '#ffad00'
blue = '#63c3dd'
magenta = '#e79cfb'
cyan = '#63c3dd'
white = '#e0e0e0'