[[themes]]
name = "MilkOutside"
[themes.palette]
background = "#040607"
foreground = "#e8e8e8"
black = "#000000"
red = "#fda1a0"
green = "#92cf9c"
yellow = "#f8e063"
blue = "#63c3dd"
magenta = "#e79cfb"
cyan = "#7dcfff"
white = "#e8e8e8"
bright_black = "#303030"
bright_red = "#e45555"
bright_green = "#5dd48c"
bright_yellow = "#ffad00"
bright_blue = "#62b9e8"
bright_magenta = "#f93a82"
bright_cyan = "#4fd1e0"
bright_white = "#e8e8e8"
