attribute = { fg = "#7dcfff" }
comment = { fg = "#595959", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "#f8e063" }
constant = { fg = "#ffad00" }
"constant.builtin" = { fg = "#62b9e8" }
"constant.builtin.boolean" = { fg = "#ffad00" }
"constant.character" = { fg = "#92cf9c" }
"constant.character.escape" = { fg = "#e79cfb" }
"constant.numeric" = { fg = "#ffad00" }
"constant.numeric.float" = { fg = "#ffad00" }
"constant.numeric.integer" = { fg = "#ffad00" }
constructor = { fg = "#62b9e8" }
"diagnostic.error" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diff.delta" = { bg = "#1a1e2e", fg = "#6183bb" }
"diff.delta.moved" = { fg = "#63c3dd" }
"diff.minus" = { bg = "#1a1e2e", fg = "#e45555" }
"diff.plus" = { bg = "#1a1e2e", fg = "#449dab" }
error = { fg = "#e45555" }
function = { fg = "#63c3dd" }
"function.builtin" = { fg = "#62b9e8" }
"function.macro" = { fg = "#7dcfff" }
"function.method" = { fg = "#63c3dd" }
"function.special" = { fg = "#7dcfff" }
hint = { fg = "#1abc9c" }
info = { fg = "#62b9e8" }
keyword = { fg = "#9d7cd8", modifiers = ["italic"] }
"keyword.control" = { fg = "#e45555" }
"keyword.control.conditional" = { fg = "#e45555" }
"keyword.control.exception" = { fg = "#e45555" }
"keyword.control.repeat" = { fg = "#e45555" }
"keyword.control.return" = { fg = "#9d7cd8", modifiers = ["italic"] }
"keyword.directive" = { fg = "#7dcfff" }
"keyword.function" = { fg = "#e45555" }
"keyword.operator" = { fg = "#e45555" }
label = { fg = "#63c3dd" }
"markup.bold" = { fg = "#c0caf5", modifiers = ["bold"] }
"markup.heading" = { fg = "#7aa2f7", modifiers = ["bold"] }
"markup.heading.completion" = { bg = "#1f2335", fg = "#c0caf5" }
"markup.heading.hover" = { bg = "#363d59" }
"markup.italic" = { fg = "#c0caf5", modifiers = ["italic"] }
"markup.link" = { fg = "#1abc9c" }
"markup.link.label" = { fg = "#2ac3de" }
"markup.link.text" = { fg = "#1abc9c" }
"markup.link.url" = { underline = { style = "line" } }
"markup.list" = { fg = "#89ddff" }
"markup.normal.completion" = { fg = "#565f89" }
"markup.normal.hover" = { fg = "#a9b1d6" }
"markup.raw" = { fg = "#92cf9c" }
"markup.raw.inline" = { bg = "#303030", fg = "#63c3dd" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
namespace = { fg = "#7dcfff" }
operator = { fg = "#4fd1e0" }
special = { fg = "#62b9e8" }
string = { fg = "#92cf9c" }
"string.regexp" = { fg = "#daffff" }
"string.special" = { fg = "#62b9e8" }
tag = { fg = "#e79cfb" }
type = { fg = "#62b9e8" }
"type.builtin" = { fg = "#29a4bd" }
"type.enum" = { fg = "#62b9e8" }
"type.enum.variant" = { fg = "#ffad00" }
"ui.background" = { bg = "bg" }
"ui.bufferline.active" = { bg = "bg_visual", fg = "fg" }
"ui.cursor" = { bg = "#e8e8e8", fg = "#040607" }
"ui.cursor.match" = { fg = "#ffad00", modifiers = ["bold"] }
"ui.linenr" = { fg = "#303030" }
"ui.linenr.select" = { fg = "#ffad00", modifiers = ["bold"] }
"ui.menu" = { bg = "#000000", fg = "#e8e8e8" }
"ui.menu.scroll" = { bg = 2566975, fg = 3883617 }
"ui.menu.selected" = { bg = "#1a1e2e" }
"ui.popup" = { bg = "#000000", fg = "#29a4bd" }
"ui.selection" = { bg = "bg_highlight" }
"ui.statusline" = { bg = "#000000", fg = "#e0e0e0" }
"ui.statusline.inactive" = { bg = "#000000", fg = "#303030" }
"ui.statusline.normal" = { bg = "blue", fg = "black" }
"ui.text" = { bg = "#040607", fg = "#e8e8e8" }
"ui.text.focus" = { bg = "#394b70" }
"ui.text.inactive" = { fg = "#595959", modifiers = ["italic"] }
"ui.text.info" = { bg = "#000000", fg = "#e8e8e8" }
"ui.virtual.inlay-hint" = { bg = "#1a1e2e", fg = "#1abc9c" }
"ui.window" = { fg = "#000000", modifiers = ["bold"] }
variable = { fg = "#e8e8e8" }
"variable.builtin" = { fg = "#e45555" }
"variable.other.member" = { fg = "#62b9e8" }
"variable.parameter" = { fg = "#f8e063" }
warning = { fg = "#f8e063" }

[palette]
bg = "#040607"
bg_dark = "#000000"
bg_dark1 = "#1a1e2e"
bg_float = "#000000"
bg_highlight = "#0f0f15"
bg_popup = "#000000"
bg_search = "#0f0f15"
bg_sidebar = "#000000"
bg_statusline = "#000000"
bg_visual = "#394b70"
black = "#000000"
blue = "#63c3dd"
blue0 = "#48b5c7"
blue1 = "#4fd1e0"
blue2 = "#62b9e8"
blue5 = "#a7e3ff"
blue6 = "#daffff"
blue7 = "#394b70"
border = "#303030"
border_highlight = "#e45555"
comment = "#595959"
cyan = "#7dcfff"
dark3 = "#303030"
dark5 = "#474747"
"diff.add" = "#292e42"
"diff.change" = "#292e42"
"diff.delete" = "#292e42"
"diff.text" = "#394b70"
error = "#e45555"
fg = "#e8e8e8"
fg_dark = "#e0e0e0"
fg_float = "#e8e8e8"
fg_gutter = "#595959"
fg_sidebar = "#e0e0e0"
"git.add" = "#449dab"
"git.change" = "#6183bb"
"git.delete" = "#914c54"
"git.ignore" = "#303030"
green = "#92cf9c"
green1 = "#5dd48c"
green2 = "#3a9b6d"
hint = "#1abc9c"
info = "#62b9e8"
magenta = "#e79cfb"
magenta2 = "#f93a82"
orange = "#ffad00"
purple = "#9d7cd8"
rainbow = "#63c3dd"
"rainbow.2" = "#f8e063"
"rainbow.3" = "#92cf9c"
"rainbow.4" = "#1abc9c"
"rainbow.5" = "#e79cfb"
"rainbow.6" = "#9d7cd8"
"rainbow.7" = "#ffad00"
"rainbow.8" = "#e45555"
red = "#e45555"
red1 = "#e45555"
teal = "#1abc9c"
"terminal.black" = "#000000"
"terminal.black_bright" = "#414868"
"terminal.blue" = "#7aa2f7"
"terminal.blue_bright" = "#8db0ff"
"terminal.cyan" = "#7dcfff"
"terminal.cyan_bright" = "#a4daff"
"terminal.green" = "#9ece6a"
"terminal.green_bright" = "#9fe044"
"terminal.magenta" = "#bb9af7"
"terminal.magenta_bright" = "#c7a9ff"
"terminal.red" = "#f7768e"
"terminal.red_bright" = "#ff899d"
"terminal.white" = "#a9b1d6"
"terminal.white_bright" = "#c0caf5"
"terminal.yellow" = "#e0af68"
"terminal.yellow_bright" = "#faba4a"
terminal_black = "#414868"
todo = "#7aa2f7"
warning = "#e0af68"
yellow = "#e0af68"