[mgr]
# NOTE: can be combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

cwd = { fg = "#e8e8e8", italic = true }

# Hovered
hovered         = { bg = "#0f0f15" }
preview_hovered = { bg = "#0f0f15" }

# Find
find_keyword  = { fg = "#000000", bg = "#ffad00", bold = true }
find_position = { fg = "#62b9e8", bg = "#292e42", bold = true }

# Marker
marker_copied   = { fg = "#92cf9c", bg = "#92cf9c" }
marker_cut      = { fg = "#e45555", bg = "#e45555" }
marker_marked   = { fg = "#e79cfb", bg = "#e79cfb" }
marker_selected = { fg = "#63c3dd", bg = "#63c3dd" }

# Count
count_copied   = { fg = "#000000", bg = "#92cf9c" }
count_cut      = { fg = "#000000", bg = "#e45555" }
count_selected = { fg = "#000000", bg = "#63c3dd" }

# Border
border_symbol = "│"
border_style  = { fg = "#e45555" }

# Tab
[tabs]
active   = { fg = "#000000", bg = "#63c3dd" }
inactive = { fg = "#63c3dd", bg = "#474747" }

[mode]
normal_main = { fg = "#000000", bg = "#63c3dd", bold = true }
normal_alt  = { fg = "#63c3dd", bg = "#474747" }

select_main = { fg = "#000000", bg = "#e79cfb", bold = true }
select_alt  = { fg = "#e79cfb", bg = "#474747" }

unset_main  = { fg = "#000000", bg = "#9d7cd8", bold = true }
unset_alt   = { fg = "#9d7cd8", bg = "#474747" }

[status]
overall   = { fg = "#e8e8e8", bg = "#303030" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label  = { fg = "#e8e8e8", bold = true }
progress_normal = { fg = "#63c3dd", bg = "#0f0f15" }
progress_error  = { fg = "#e45555", bg = "#0f0f15" }

# Permissions
perm_type  = { fg = "#63c3dd" }
perm_read  = { fg = "#f8e063" }
perm_write = { fg = "#e45555" }
perm_exec  = { fg = "#92cf9c" }
perm_sep   = { fg = "#303030" }

[pick]
border   = { fg = "#e45555" }
active   = { fg = "#e8e8e8",  bg = "#394b70" }
inactive = { fg = "#e8e8e8" }

# Input
[input]
border   = { fg = "#62b9e8" }
title    = { fg = "#62b9e8" }
value    = { fg = "#9d7cd8" }
selected = { bg = "#394b70" }

# Completion
[cmp]
border   = { fg = "#62b9e8" }
active   = { fg = "#e8e8e8", bg = "#1a1e2e" }
inactive = { fg = "#e8e8e8" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#e45555" }
title   = { fg = "#e45555" }
hovered = { fg = "#e8e8e8", bg = "#394b70" }

# Which
[which]
cols            = 3
mask            = { bg = "#303030" }
cand            = { fg = "#7dcfff" }
rest            = { fg = "#63c3dd" }
desc            = { fg = "#e79cfb" }
separator       = " ➜ "
separator_style = { fg = "#595959" }

# Confirm
[confirm]
border  = { fg = "#62b9e8" }
title   = { fg = "#e45555" }
content = {}
list    = {}
btn_yes = { bg = "#394b70" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#e45555" }
title   = { fg = "#e45555" }

# Notify
[notify]
title_info  = { fg = "#62b9e8" }
title_warn  = { fg = "#f8e063" }
title_error = { fg = "#e45555" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#92cf9c" }
run     = { fg = "#e79cfb" }
desc    = { fg = "#7dcfff" }
hovered = { bg = "#0f0f15" }
footer  = { fg = "#e8e8e8", bg = "#000000" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#f8e063" },

	# Media
	{ mime = "{audio,video}/*", fg = "#e79cfb" },

	# Archives
	{ mime = "application/*zip", fg = "#e45555" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#e45555" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#7dcfff" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#e45555" },

	# Special files
	{ name = "*", is = "orphan", bg = "#e45555" },
	{ name = "*", is = "exec"  , fg = "#92cf9c" },

	# Fallback
	{ name = "*/", fg = "#63c3dd" },
	{ name = "*", fg = "#e8e8e8" }
]
    